nsexec
okuda-seminar/docker_internal pull request #2
Opened 2023-01-29 15:26 UTC by nayuta-ai

## Implementation Summary
I implemented [a clone_parent function](https://github.com/nayuta-ai/docker_internal/blob/nsexec/clone_parent/src/nsexec.c) and [a test file corresponding to the clone_parent](https://github.com/nayuta-ai/docker_internal/blob/nsexec/clone_parent/tests/C/main.cpp).

## Scope of Impact
The clone_parent creates a child process, and both processes continuously run.

## Particular points to check
I would appreciate your comments on whether there is any information missing about README or the commits.

## Test
We can test each function by using the following command:
```
$ git clone https://github.com/nayuta-ai/docker_internal.git
$ cd docker_internal
$ git checkout nsexec/clone_parent
$ make build
$ make run
$ make exec
$ cd tests/C
$ cmake .
$ make
$ ./example_test
```

2023-02-14 04:13 UTC, ryuji0123 requested changes
Basically, your code seems fine. Please check my comments.

2023-02-14 04:13 UTC, ryuji0123 commented on doc/nsenter.md
> +$ git checkout nsexec/clone_parent
git checkout nsexec

2023-02-14 04:13 UTC, ryuji0123 commented on go.mod
> +module docker_internal
Do we need this file in this PR?

2023-02-14 04:13 UTC, ryuji0123 commented on src/nsexec.c
> +	/* There's two children. This is used to execute the different code. */
Maybe
This is -> They are

2023-02-14 14:16 UTC, ryuji0123 requested changes

2023-02-14 14:16 UTC, ryuji0123 commented on doc/nsenter.md
> +$ ./example_test
example_test -> nsexec_test

2023-02-14 14:30 UTC, ryuji0123 requested changes

2023-02-14 14:30 UTC, ryuji0123 commented on tests/C/main.cpp
>  #include <gtest/gtest.h>
Let's follow [this style](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes).

2023-02-15 08:06 UTC, nayuta723 commented on doc/nsenter.md
> +$ git checkout nsexec/clone_parent
I used nsexec/clone_parent tag for switching source code. Is it preferable to change the source code on a per-branch basis?

2023-02-15 09:51 UTC, nayuta-ai commented
@ryuji0123 
I modified the previous one to the directory structure, which summarizes the "src" and "test" directories in one director. But the different points are no longer visible. I know this is hard to review, but please comment on that.

2023-02-16 13:31 UTC, ryuji0123 commented
@nayuta-ai 
As I told you before, you can resolve conversations first, to show what you've modified.

2023-02-16 13:44 UTC, ryuji0123 requested changes

2023-02-16 13:44 UTC, ryuji0123 commented on .gitignore
> +build
"build/" and "build" is different. This line should be "build/". You should also check the difference.

2023-02-16 13:44 UTC, ryuji0123 commented on doc/nsenter.md
> +$ git checkout nsexec/clone_parent
I see. In that case, we should fetch the tag before checking out.

2023-02-16 13:44 UTC, ryuji0123 commented on nsexec/src/nsexec.h
> +	/*
About indent spaces, you can see [this](https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs). It is also the same case with other files.

2023-02-21 06:57 UTC, ryuji0123 requested changes

2023-02-21 06:57 UTC, ryuji0123 commented on nsexec/src/nsexec.h
> +static int child_func(void *arg)
https://github.com/okuda-seminar/Engineering/issues/661#issuecomment-1434276807

2023-03-02 15:38 UTC, ryuji0123 approved these changes
LGTM

2023-03-02 15:39 UTC, merged